name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install python requirements
      run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Run pylint
      # Ignore Qt designer generated ui_*.py files
      run: |
        find pycovering tests -name '*.py' -not -name '*ui_*.py' | xargs pylint
